### PR TITLE
feat(utils): add make func & clean code

### PR DESCRIPTION
**Pull request by nonzzz**
## Checklist

---

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information

---

For more performance. I decide add a make func. You can see it's very clean.

### CODE REVIEW

**Comment by zaunist** [comment]
I don't think we need to bring the golang code style into typescript, it makes the code look a little strange.

**Comment by zaunist** [comment]
Of course, there's nothing wrong with coding it that way if you must.

**Comment by nonzzz** [comment]
@zaunist There is a reason for why i 
need a make func, you can view some component use [...Array]，But is not
a good way, form the benchmark.make 
is more fast

**Comment by nonzzz** [comment]
expand operator is easy cause stack 
explosion. We should avoid

**Comment by zaunist** [comment]
JS Benchmarks:
https://perf.link/#eyJpZCI6ImQ4bnBoNTV0OHg1IiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IG1ha2UgPSAoY2FwKT0%2BbmV3IEFycmF5KGNhcCkuZmlsbCh1bmRlZmluZWQpO1xuY29uc3QgbWFrZXMgPShjYXApPT5bLi4ubmV3IEFycmF5KGNhcCldOyIsInRlc3RzIjpbeyJuYW1lIjoibm9ybWFsIiwiY29kZSI6Im1ha2UoMTAwMDAwMDApIiwicnVucyI6WzI5LDI5LDI5LDI5LDI5LDI5LDI5LDI5LDI3LDI5LDI5LDI5LDI3LDI5LDI5LDI3LDI5LDI5LDI5LDI3LDI3LDI5LDI2LDI5LDI2LDI3LDI3LDI5LDI2LDI5LDI5LDI5LDI3LDI3LDI5LDI2LDI0LDI0LDI2LDI3LDI5LDI5LDI3LDI5LDI5LDI5LDI5LDI3LDI2LDI3LDI3LDI5LDI3LDI5LDI3LDI5LDI3LDI3LDI5LDI3LDI5LDI5LDI3LDI5LDI5LDI5LDI3LDI5LDI3LDI5LDI5LDI3LDI5LDI5LDI5LDI5LDI3LDI5LDI5LDI5LDI5LDI5LDI5LDI5LDI5LDI5LDI3LDI3LDI3LDI3LDI5LDI2LDI5LDI5LDI5LDI2LDI5LDI3LDMxLDI3XSwib3BzIjoyOH0seyJuYW1lIjoic3BlYXRvciIsImNvZGUiOiJtYWtlcygxMDAwMDAwMCkiLCJydW5zIjpbMTcsMTcsMTcsMTcsMTUsMTcsMTcsMTcsMTUsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTUsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTUsMTUsMTUsMTUsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTUsMTUsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTcsMTksMTcsMTcsMTcsMTldLCJvcHMiOjE2fV0sInVwZGF0ZWQiOiIyMDIyLTA1LTI3VDAyOjAzOjEyLjI0OFoifQ%3D%3D

**Review by zaunist — APPROVED** [review]

**Pull request merged**
